obj-y		+= qdsp6v2/
obj-$(CONFIG_MSM_MCU_TIME_SYNC) += mcu_time_sync.o
#sunjingtao@wind-mobi.com add for hardware info at 20180328 begin
obj-$(CONFIG_HARDWARE_INFO)		+= hardware_info/
#sunjingtao@wind-mobi.com add for hardware info at 20180328 end
