#mahui01@wind-mobi.com 2018/9/17 add for lenovo CSDK begin
#
# Makefile - WantJoin information tech co.ltd driver.
# Copyright(c) 2015, WantJoin information tech co.ltd.
#

#$(call all-subdir-src-or-makefile)
obj-$(CONFIG_WANTJOIN_FIREWALL) += wjfirewall/
#mahui01@wind-mobi.com 2018/9/17 add for lenovo CSDK end