#
# Makefile for the sysfs virtual filesystem
#
obj-y		:= file.o dir.o symlink.o mount.o group.o

#wuminglei@wind-mobi.com modify to 20180512 begin
obj-y		+= bootinfo.o
#wuminglei@wind-mobi.com modify to 20180512 end

