#
# Makefile for the sysfs virtual filesystem
#
#wuminglei@wind-mobi.com modify to 20180512 begin
obj-y		:= file.o dir.o symlink.o mount.o group.o bootinfo.o 
#wuminglei@wind-mobi.com modify to 20180512 end